# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Supermin"
license = "MIT"
licenselink = "https://github.com/amfl/hugo-supermin/blob/master/LICENSE.md"
description = "Super minimalist"
homepage = "https://github.com/amfl/hugo-supermin"
tags = ["minimal"]
features = []
min_version = 0.15

[author]
  name = "amfl"
  homepage = "https://github.com/amfl/"
